// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tokenize_cpp_fun
List tokenize_cpp_fun(std::vector<std::string> s);
RcppExport SEXP _wactor_tokenize_cpp_fun(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(tokenize_cpp_fun(s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wactor_tokenize_cpp_fun", (DL_FUNC) &_wactor_tokenize_cpp_fun, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_wactor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
