# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tokenize_cpp_fun <- function(s) {
    .Call(`_wactor_tokenize_cpp_fun`, s)
}

