# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppvariance <- function(x, narm = TRUE) {
    .Call(`_wactor_cppvariance`, x, narm)
}

