# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppvar <- function(x, narm = TRUE) {
    .Call(`_wactor_cppvar`, x, narm)
}

cppsd <- function(x, narm = TRUE) {
    .Call(`_wactor_cppsd`, x, narm)
}

cppmean <- function(x, narm = TRUE) {
    .Call(`_wactor_cppmean`, x, narm)
}

